### PR TITLE
fix: add tsconfig option noUncheckedIndexedAccess

### LINKED ISSUE #1: enable tsconfig option `noUncheckedIndexedAccess`
I think you should enable this option, as the lack of it crashes my Typescript application.
I have a PR ready for you, if you want.

### PR DESCRIPTION
**Pull request by aorsten**
Fixes #1

### CODE REVIEW

File: src/nestLists.ts [hunk 1]
```diff
@@ -60,6 +60,9 @@ export function nestLists<T extends TypedObject = PortableTextBlock | TypedObjec
 
   for (let i = 0; i < blocks.length; i++) {
     const block = blocks[i]
+    if (!block) {
+      continue
```
Comment (aorsten) [inline src/nestLists.ts:64]: This is meant to guard the block from being `undefined`. Perhaps throwing is better than `continue`.

**Review by rexxars — APPROVED** [review]

**Comment by rexxars** [comment]
Great work! Thanks for raising and fixing!

**Comment by rexxars** [comment]
Released as part of [1.0.4](https://github.com/portabletext/toolkit/commit/955d3e9acc45ea8091dd06ba2923e32474830a00)
